name: Compile Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Java 21 # <--- CAMBIADO DE 17 A 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'   # <--- CAMBIADO DE 17 A 21
          distribution: 'temurin'
          cache: gradle

      - name: Dar permisos a Gradlew
        run: chmod +x gradlew

      - name: Compilar APK (fDroid Debug)
        run: ./gradlew assembleFDroidDebug

      - name: Subir APK compilado
        uses: actions/upload-artifact@v4
        with:
          name: SmartAutoClicker-Debug-APK
          path: "**/build/outputs/apk/fDroid/debug/*.apk"
