name: Compile Android APK

on:
  push:
    branches: [ "main" ]    # Se activa al subir cambios a main
  pull_request:
    branches: [ "main" ]    # Se activa en PRs a main
  workflow_dispatch:        # <--- ESTO activa el botÃ³n "Run workflow" manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Dar permisos a Gradlew
        run: chmod +x gradlew

      - name: Compilar APK (fDroid Debug)
        run: ./gradlew assembleFDroidDebug

      - name: Subir APK compilado
        uses: actions/upload-artifact@v4
        with:
          name: SmartAutoClicker-Debug-APK
          path: "**/build/outputs/apk/fDroid/debug/*.apk" # Ruta mejorada para encontrar el archivo